In [1]:
# Q.1 -- Create a Numpy 'arr' of integers from 0 to 5 and print its data type.
# Ans -- 
import numpy as np

# Create the NumPy array
arr = np.arange(6)

# Print the array and its data type
print("Array:", arr)
print("Data type:", arr.dtype)


Array: [0 1 2 3 4 5]
Data type: int64


In [2]:
# Q.2 -- Given a Numpy array 'arr' check if its data type is float64.
#   arr = np.array([1.5, 2.6, 3.7])
# Ans -- 
import numpy as np

# Create the NumPy array
arr = np.array([1.5, 2.6, 3.7])

# Check if the data type is float64
is_float64 = arr.dtype == np.float64

# Print the result
print("Is the data type float64?", is_float64)


Is the data type float64? True


In [3]:
# Q.3 -- Create a Numpy array 'arr' with a data type of somplex128 containing three complex numbers.
# Ans -- 
import numpy as np

# Create the NumPy array with complex128 data type
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# Print the array and its data type
print("Array:", arr)
print("Data type:", arr.dtype)


Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


In [4]:
# Q.4 -- Convert an  existing Numpy array 'arr' of integers to float32 data type.
# Ans --
import numpy as np

# Example existing array of integers
arr = np.array([1, 2, 3, 4, 5])

# Convert the array to float32
arr_float32 = arr.astype(np.float32)

# Print the converted array and its data type
print("Converted Array:", arr_float32)
print("Data type:", arr_float32.dtype)


Converted Array: [1. 2. 3. 4. 5.]
Data type: float32


In [5]:
# Q.5 -- Given a Numpy array 'arr' with float64 data type, convert it to float32 to reduce decimal numbers.
# Ans -- 
import numpy as np

# Example existing array with float64 data type
arr = np.array([1.123456789, 2.987654321, 3.141592653], dtype=np.float64)

# Convert the array to float32
arr_float32 = arr.astype(np.float32)

# Print the converted array and its data type
print("Original Array (float64):", arr)
print("Converted Array (float32):", arr_float32)
print("Original Data Type:", arr.dtype)
print("Converted Data Type:", arr_float32.dtype)


Original Array (float64): [1.12345679 2.98765432 3.14159265]
Converted Array (float32): [1.1234568 2.9876542 3.1415927]
Original Data Type: float64
Converted Data Type: float32


In [6]:
# Q.6 -- Write a function array_attributes that takes a Numpy array as input and returnd its shape, size, and data type.
# Ans -- 
import numpy as np

def array_attributes(arr):
    """
    Function to return the shape, size, and data type of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array.

    Returns:
    tuple: A tuple containing the shape, size, and data type of the array.
    """
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
shape, size, dtype = array_attributes(arr)

print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)


Shape: (2, 3)
Size: 6
Data type: float32


In [7]:
# Q.7 -- Create a function array_dimension that takes a Numpy array as input and returnd its dimensionality.
# Ans -- 
import numpy as np

def array_dimension(arr):
    """
    Function to return the dimensionality of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array.

    Returns:
    int: The number of dimensions of the array.
    """
    return arr.ndim

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
dim = array_dimension(arr)

print("Dimensionality:", dim)


Dimensionality: 2


In [8]:
# Q.8. -- Design a function item_size_info that takes a Numpy array as input and returns the item size and the total size in bytes.
# Ans --
import numpy as np

def item_size_info(arr):
    """
    Function to return the size of each item and the total size of a NumPy array in bytes.

    Parameters:
    arr (numpy.ndarray): Input NumPy array.

    Returns:
    tuple: A tuple containing the size of each item in bytes and the total size of the array in bytes.
    """
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
item_size, total_size = item_size_info(arr)

print("Size of each item (in bytes):", item_size)
print("Total size of the array (in bytes):", total_size)


Size of each item (in bytes): 4
Total size of the array (in bytes): 24


In [9]:
# Q.9 -- Create a function array_strides that takes a Numpy array as input and returns the strides of the array.
# Ans -- 
import numpy as np

def array_strides(arr):
    """
    Function to return the strides of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array.

    Returns:
    tuple: A tuple containing the strides of the array in bytes.
    """
    return arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)

print("Strides of the array (in bytes):", strides)


Strides of the array (in bytes): (24, 8)


In [10]:
# Q.10 -- Design a function shape_stride_relationship that takes a Numpy array as input and returns the shape and strides of the array.
# Ans -- 
import numpy as np

def shape_stride_relationship(arr):
    """
    Function to return the shape and strides of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array.

    Returns:
    tuple: A tuple containing two elements:
           - The shape of the array.
           - The strides of the array.
    """
    shape = arr.shape
    strides = arr.strides
    return shape, strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)

print("Shape of the array:", shape)
print("Strides of the array (in bytes):", strides)


Shape of the array: (2, 3)
Strides of the array (in bytes): (24, 8)


In [11]:
# Q.11 -- Create a function 'create_zeros_array' that takes an integer 'n' as input and returns a NumPy array of zeros with 'n' elements.
# Ans -- 
import numpy as np

def create_zeros_array(n):
    """
    Function to create a NumPy array of zeros with 'n' elements.

    Parameters:
    n (int): The number of elements in the array.

    Returns:
    numpy.ndarray: A NumPy array of zeros with 'n' elements.
    """
    return np.zeros(n)

# Example usage
n = 5
zeros_array = create_zeros_array(n)

print("Array of zeros:", zeros_array)


Array of zeros: [0. 0. 0. 0. 0.]


In [12]:
# Q.12 Write a function 'create_ones_matrix' that takes integer 'rows' and 'cols' as inputs and generates a 2D NumPy array filled with ones of size 'rows x cols'.
# Ans -- 
import numpy as np

def create_ones_matrix(rows, cols):
    """
    Function to create a 2D NumPy array filled with ones with the specified number of rows and columns.

    Parameters:
    rows (int): The number of rows in the matrix.
    cols (int): The number of columns in the matrix.

    Returns:
    numpy.ndarray: A 2D NumPy array of ones with shape (rows, cols).
    """
    return np.ones((rows, cols))

# Example usage
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)

print("Matrix of ones:")
print(ones_matrix)



Matrix of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# Q.13. Write a function  `generate_range_array` that takes three integers start, stop, and step as arguments and
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.
# Ans --
import numpy as np

def generate_range_array(start, stop, step):
    """
    Function to generate a NumPy array with a range starting from 'start',
    ending at 'stop' (exclusive), and with the specified 'step'.

    Parameters:
    start (int): The starting value of the range.
    stop (int): The end value of the range (exclusive).
    step (int): The step between values in the range.

    Returns:
    numpy.ndarray: A NumPy array with the specified range.
    """
    return np.arange(start, stop, step)

# Example usage
start = 1
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)

print("Range array:", range_array)


Range array: [1 3 5 7 9]


In [14]:
# Q.14 -- Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
# Ans -- 
import numpy as np

def generate_linear_space(start, stop, num):
    """
    Function to generate a NumPy array with 'num' equally spaced values between 'start' and 'stop' (inclusive).

    Parameters:
    start (float): The starting value of the range.
    stop (float): The ending value of the range (inclusive).
    num (int): The number of equally spaced values to generate.

    Returns:
    numpy.ndarray: A NumPy array with 'num' equally spaced values between 'start' and 'stop'.
    """
    return np.linspace(start, stop, num)

# Example usage
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)

print("Linear space array:", linear_space_array)


Linear space array: [0.   0.25 0.5  0.75 1.  ]


In [15]:
# Q.15. -- Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
# Ans -- 
import numpy as np

def create_identity_matrix(n):
    """
    Function to generate a square identity matrix of size 'n x n'.

    Parameters:
    n (int): The size of the identity matrix.

    Returns:
    numpy.ndarray: A square identity matrix of size 'n x n'.
    """
    return np.eye(n)

# Example usage
n = 4
identity_matrix = create_identity_matrix(n)

print("Identity matrix:")
print(identity_matrix)


Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# Q.16 -- Write a function that takes a Python list and converts it into a NumPy array.
# Ans -- 
import numpy as np

def list_to_array(py_list):
    """
    Function to convert a Python list into a NumPy array.

    Parameters:
    py_list (list): The Python list to convert.

    Returns:
    numpy.ndarray: The converted NumPy array.
    """
    return np.array(py_list)

# Example usage
py_list = [1, 2, 3, 4, 5]
array = list_to_array(py_list)

print("NumPy array:", array)
print("Data type of NumPy array:", array.dtype)


NumPy array: [1 2 3 4 5]
Data type of NumPy array: int64


In [17]:
# Q.17 -- Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data. 
# Ans-- 
import numpy as np

# Create a NumPy array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a new view of the original array
view_array = original_array.view()

# Modify the new view array
view_array[0, 0] = 10

# Print the original and view arrays to demonstrate they share the same data
print("Original array:")
print(original_array)

print("View array:")
print(view_array)


Original array:
[[10  2  3]
 [ 4  5  6]]
View array:
[[10  2  3]
 [ 4  5  6]]


In [18]:
# Q.18 -- Write a function that takes two NumPy arrays and concatenates them along a specified axis.
# Ans -- 
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    """
    Function to concatenate two NumPy arrays along a specified axis.

    Parameters:
    arr1 (numpy.ndarray): The first NumPy array.
    arr2 (numpy.ndarray): The second NumPy array.
    axis (int): The axis along which to concatenate the arrays. Default is 0.

    Returns:
    numpy.ndarray: The concatenated NumPy array.
    """
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate along axis 0 (rows)
concatenated_axis0 = concatenate_arrays(arr1, arr2, axis=0)

# Concatenate along axis 1 (columns)
concatenated_axis1 = concatenate_arrays(arr1, arr2, axis=1)

print("Concatenated along axis 0:")
print(concatenated_axis0)

print("Concatenated along axis 1:")
print(concatenated_axis1)


Concatenated along axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenated along axis 1:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [19]:
# Q.19 -- Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
# Ans -- 
import numpy as np

# Create two NumPy arrays with compatible shapes for horizontal concatenation
arr1 = np.array([[1, 2, 3], [4, 5, 6]])   # Shape (2, 3)
arr2 = np.array([[7, 8], [9, 10]])        # Shape (2, 2)

# Concatenate arrays horizontally (along axis 1)
concatenated_array = np.concatenate((arr1, arr2), axis=1)

print("Concatenated horizontally:")
print(concatenated_array)


Concatenated horizontally:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [20]:
# Q.20 -- Write a function that vertically stacks multiple NumPy arrays given as a list. 
# Ans -- 
import numpy as np

def stack_arrays_vertically(array_list):
    """
    Function to vertically stack multiple NumPy arrays given as a list.

    Parameters:
    array_list (list of numpy.ndarray): List of NumPy arrays to stack vertically.

    Returns:
    numpy.ndarray: A single NumPy array resulting from vertical stacking of the input arrays.
    """
    return np.vstack(array_list)

# Example usage
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr3 = np.array([[13, 14, 15]])

# List of arrays to stack
arrays_to_stack = [arr1, arr2, arr3]

# Stack arrays vertically
stacked_array = stack_arrays_vertically(arrays_to_stack)

print("Vertically stacked array:")
print(stacked_array)


Vertically stacked array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [21]:
# Q.21 --  Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
# Ans -- 
import numpy as np

def create_range_array(start, stop, step):
    """
    Function to create an array of integers within a specified range (inclusive) with a given step size.

    Parameters:
    start (int): The starting value of the range.
    stop (int): The ending value of the range (inclusive).
    step (int): The step size between values in the range.

    Returns:
    numpy.ndarray: A NumPy array of integers within the specified range.
    """
    # Adjust the stop value to be inclusive
    adjusted_stop = stop + step
    
    # Create the array using np.arange
    return np.arange(start, adjusted_stop, step)

# Example usage
start = 1
stop = 10
step = 2
range_array = create_range_array(start, stop, step)

print("Array within range:")
print(range_array)


Array within range:
[ 1  3  5  7  9 11]


In [22]:
# Q22. -- Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
# Ans -- 
import numpy as np

def generate_equally_spaced_values(start, stop, num):
    """
    Function to generate an array of equally spaced values between 'start' and 'stop' (inclusive).

    Parameters:
    start (float): The starting value of the range.
    stop (float): The ending value of the range (inclusive).
    num (int): The number of equally spaced values to generate.

    Returns:
    numpy.ndarray: A NumPy array of equally spaced values.
    """
    return np.linspace(start, stop, num)

# Example usage
start = 0
stop = 1
num = 10
equally_spaced_values = generate_equally_spaced_values(start, stop, num)

print("Array of equally spaced values:")
print(equally_spaced_values)


Array of equally spaced values:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
# Q.23 -- Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
# Ans -- 
import numpy as np

def create_logarithmically_spaced_values(start, stop, num):
    """
    Function to create an array of logarithmically spaced values between 'start' and 'stop' (inclusive).

    Parameters:
    start (float): The starting value (exponent of the base 10).
    stop (float): The ending value (exponent of the base 10).
    num (int): The number of logarithmically spaced values to generate.

    Returns:
    numpy.ndarray: A NumPy array of logarithmically spaced values.
    """
    return np.logspace(start, stop, num)

# Example usage
start_exponent = 0  # log10(1)
stop_exponent = 3   # log10(1000)
num_values = 5

logarithmically_spaced_values = create_logarithmically_spaced_values(start_exponent, stop_exponent, num_values)

print("Array of logarithmically spaced values:")
print(logarithmically_spaced_values)


Array of logarithmically spaced values:
[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [24]:
# Q.24 --  Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
# Ans -- 
import numpy as np
import pandas as pd

def create_dataframe_from_random_array(rows, cols, min_val, max_val):
    """
    Function to create a Pandas DataFrame from a NumPy array with random integers.

    Parameters:
    rows (int): The number of rows in the DataFrame.
    cols (int): The number of columns in the DataFrame.
    min_val (int): The minimum value for the random integers.
    max_val (int): The maximum value for the random integers.

    Returns:
    pandas.DataFrame: A DataFrame created from the random integers array.
    """
    # Generate a NumPy array with random integers
    random_array = np.random.randint(min_val, max_val + 1, size=(rows, cols))
    
    # Create a DataFrame from the NumPy array
    df = pd.DataFrame(random_array, columns=[f'Column_{i+1}' for i in range(cols)])
    
    return df

# Example usage
rows = 5
cols = 3
min_val = 1
max_val = 100

df = create_dataframe_from_random_array(rows, cols, min_val, max_val)

print("DataFrame with random integers:")
print(df)


DataFrame with random integers:
   Column_1  Column_2  Column_3
0        97        13        99
1        14        29         5
2        23        42         3
3        91        41        22
4        68        67        51


In [25]:
# Q.25 -- Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
# Ans -- 
import pandas as pd
import numpy as np

def replace_negative_values(df, column_name):
    """
    Function to replace all negative values in a specific column of a Pandas DataFrame with zeros.

    Parameters:
    df (pandas.DataFrame): The DataFrame containing the data.
    column_name (str): The name of the column in which to replace negative values.

    Returns:
    pandas.DataFrame: The DataFrame with negative values replaced by zeros in the specified column.
    """
    if column_name in df.columns:
        # Use NumPy to replace negative values with zeros
        df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    else:
        raise ValueError(f"Column '{column_name}' does not exist in the DataFrame.")
    
    return df

# Example usage
data = {
    'A': [10, -5, 3, -1, 2],
    'B': [-4, -3, 6, 2, -8],
    'C': [7, -9, 2, 3, -4]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Replace negative values in column 'A'
df_modified = replace_negative_values(df, 'A')

print("\nDataFrame after replacing negative values in column 'A':")
print(df_modified)


Original DataFrame:
    A  B  C
0  10 -4  7
1  -5 -3 -9
2   3  6  2
3  -1  2  3
4   2 -8 -4

DataFrame after replacing negative values in column 'A':
    A  B  C
0  10 -4  7
1   0 -3 -9
2   3  6  2
3   0  2  3
4   2 -8 -4


In [26]:
# Q.26 --  Access the 3rd element from the given NumPy array.
          # arr = np.array([10, 20, 30, 40, 50])
#Ans -- 
import numpy as np

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

print("The 3rd element is:", third_element)


The 3rd element is: 30


In [28]:
# Q.27 -- Retrieve the element at index (1, 2) from the 2D NumPy array.
       
      # arr_2d = np.array([[1, 2, 3],
               #    [4, 5, 6],
                #   [7, 8, 9]])            
# Ans --
import numpy as np

# Given 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Retrieve the element at index (1, 2)
element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)


The element at index (1, 2) is: 6


In [30]:
# Q.28 --  Using boolean indexing, extract elements greater than 5 from the given NumPy array.
                   # arr = np.array([3, 8, 2, 10, 5, 7])
# Ans -- 
import numpy as np

# Given NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])

# Create a boolean mask for elements greater than 5
boolean_mask = arr > 5

# Use the boolean mask to extract elements greater than 5
elements_greater_than_5 = arr[boolean_mask]

print("Elements greater than 5 are:", elements_greater_than_5)


Elements greater than 5 are: [ 8 10  7]


In [31]:
# Q.29 -- Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
   # arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Ans -- 
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Perform basic slicing to extract elements from index 2 to 5 (inclusive)
# Note that slicing is end-exclusive, so we need to specify 6 to include index 5
sliced_elements = arr[2:6]

print("Elements from index 2 to 5 (inclusive) are:", sliced_elements)


Elements from index 2 to 5 (inclusive) are: [3 4 5 6]


In [33]:
# Q30. -- Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
                                        # arr_2d = np.array([[1, 2, 3],
                                         #                   [4, 5, 6],
                                         #                   [7, 8, 9]])
# Ans --
import numpy as np

# Given 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Correct slicing to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]  # Select rows 0 to 1 and columns 1 to 2

print("Sub-array [[2, 3], [5, 6]] is:")
print(sub_array)



Sub-array [[2, 3], [5, 6]] is:
[[2 3]
 [5 6]]


In [34]:
# Q.31 -- .Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
# Ans --
import numpy as np

def extract_elements_by_indices(arr_2d, indices):
    row_indices, col_indices = indices[:, 0], indices[:, 1]
    return arr_2d[row_indices, col_indices]

# Given 2D NumPy array
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Indices to extract elements
indices = np.array([[0, 1], [1, 2], [2, 0]])

# Extract elements
extracted_elements = extract_elements_by_indices(arr_2d, indices)

print("Extracted elements are:", extracted_elements)


Extracted elements are: [20 60 70]


In [35]:
# Q.32 --  Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
# ans -- 
import numpy as np

def filter_elements_greater_than(arr, threshold):
    """
    Filter elements greater than a specified threshold from a 1D NumPy array.

    Parameters:
    arr (numpy.ndarray): The 1D NumPy array to filter.
    threshold (float): The threshold value to compare against.

    Returns:
    numpy.ndarray: A NumPy array containing elements greater than the threshold.
    """
    # Create a boolean mask where elements are greater than the threshold
    boolean_mask = arr > threshold
    
    # Use the boolean mask to filter the array
    filtered_elements = arr[boolean_mask]
    
    return filtered_elements

# Example usage
arr = np.array([1, 5, 8, 10, 15, 3])
threshold = 7
filtered_elements = filter_elements_greater_than(arr, threshold)

print("Filtered elements are:", filtered_elements)


Filtered elements are: [ 8 10 15]


In [1]:
# Q.33 --  Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
# Ans 
import numpy as np

def extract_elements(arr, i_indices, j_indices, k_indices):
    """
    Extract specific elements from a 3D NumPy array using indices provided
    in three separate arrays for each dimension.

    Parameters:
    arr (np.ndarray): A 3D NumPy array.
    i_indices (np.ndarray): Array of indices for the first dimension.
    j_indices (np.ndarray): Array of indices for the second dimension.
    k_indices (np.ndarray): Array of indices for the third dimension.

    Returns:
    np.ndarray: An array of the extracted elements.
    """
    # Ensure indices are NumPy arrays
    i_indices = np.asarray(i_indices)
    j_indices = np.asarray(j_indices)
    k_indices = np.asarray(k_indices)
    
    # Ensure all indices arrays have the same length
    if not (len(i_indices) == len(j_indices) == len(k_indices)):
        raise ValueError("All index arrays must have the same length.")

    # Extract the elements
    return arr[i_indices, j_indices, k_indices]

# Example usage:
# Create a 3D array
arr = np.arange(27).reshape(3, 3, 3)
print("Original array:")
print(arr)

# Define indices
i_indices = np.array([0, 1, 2])
j_indices = np.array([0, 1, 2])
k_indices = np.array([0, 1, 2])

# Extract elements
extracted_elements = extract_elements(arr, i_indices, j_indices, k_indices)
print("Extracted elements:")
print(extracted_elements)


Original array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Extracted elements:
[ 0 13 26]


In [3]:
# Q.34 -- Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
# Ans -- 
import numpy as np

def filter_elements(arr, condition1, condition2):
    """
    Return elements from a NumPy array where both conditions are satisfied.

    Parameters:
    arr (np.ndarray): Input NumPy array.
    condition1 (np.ndarray): Boolean array representing the first condition.
    condition2 (np.ndarray): Boolean array representing the second condition.

    Returns:
    np.ndarray: Elements from `arr` where both `condition1` and `condition2` are True.
    """
    # Ensure conditions are NumPy arrays
    condition1 = np.asarray(condition1)
    condition2 = np.asarray(condition2)
    
    # Ensure conditions have the same shape as the array
    if arr.shape != condition1.shape or arr.shape != condition2.shape:
        raise ValueError("Conditions must have the same shape as the array.")
    
    # Combine conditions using logical AND
    combined_condition = condition1 & condition2
    
    # Return elements where the combined condition is True
    return arr[combined_condition]

# Example usage:
# Create a NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Define conditions
condition1 = arr > 3         # Elements greater than 3
condition2 = arr % 2 == 0    # Elements that are even

# Filter elements
filtered_elements = filter_elements(arr, condition1, condition2)
print("Filtered elements:")
print(filtered_elements)


Filtered elements:
[4 6 8]


In [4]:
# Q.35 -- Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
# Ans --
import numpy as np

def extract_elements_2d(arr, row_indices, col_indices):
    """
    Extract elements from a 2D NumPy array using row and column indices provided in separate arrays.

    Parameters:
    arr (np.ndarray): A 2D NumPy array.
    row_indices (np.ndarray): Array of row indices.
    col_indices (np.ndarray): Array of column indices.

    Returns:
    np.ndarray: An array of the extracted elements.
    """
    # Ensure indices are NumPy arrays
    row_indices = np.asarray(row_indices)
    col_indices = np.asarray(col_indices)
    
    # Ensure indices arrays have the same length
    if len(row_indices) != len(col_indices):
        raise ValueError("Row and column indices must have the same length.")
    
    # Extract elements
    return arr[row_indices, col_indices]

# Example usage:
# Create a 2D array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Define row and column indices
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 0, 2])

# Extract elements
extracted_elements = extract_elements_2d(arr, row_indices, col_indices)
print("Extracted elements:")
print(extracted_elements)


Extracted elements:
[20 40 90]


In [5]:
# Q.36 --  Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
# Ans -- 
import numpy as np

# Create a 2D array of shape (3, 3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Scalar value to add
scalar = 5

# Add the scalar value to each element of the array
result = arr + scalar

print("Original array:")
print(arr)
print("\nArray after adding scalar value:")
print(result)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after adding scalar value:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [7]:
# Q.37 -- Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
# Ans -- 
import numpy as np

# Define the arrays
arr1 = np.array([[2, 4, 6]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  # Shape (3, 4)

# To make sure the dimensions align correctly for broadcasting, reshape arr1
# to match the dimensions of arr2 for element-wise multiplication.
# Here, arr1 is reshaped to (3, 1) to match (3, 4) for broadcasting
arr1_broadcasted = np.reshape(arr1, (3, 1))

# Multiply each row of arr2 by the corresponding element in arr1
result = arr2 * arr1_broadcasted

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult after broadcasting multiplication:")
print(result)


arr1:
[[2 4 6]]

arr2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result after broadcasting multiplication:
[[ 2  4  6  8]
 [20 24 28 32]
 [54 60 66 72]]


In [9]:
# Q.38 --  Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
# Ans --
import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])  # Shape (4, 3)

# Since arr1 has 4 columns and arr2 has 3 columns,
# we need to adjust the shapes for broadcasting.
# We can use np.reshape to match the shapes correctly.

# Reshape arr1 to (4, 1) so it can be broadcasted to match (4, 3) for addition
arr1_broadcasted = np.reshape(arr1, (4, 1))

# Add arr1 to each row of arr2
result = arr2 + arr1_broadcasted

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult after broadcasting addition:")
print(result)


arr1:
[[1 2 3 4]]

arr2:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]

Result after broadcasting addition:
[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [11]:
# Q.39 -- Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
# Ans
import numpy as np

# Define the arrays
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[10, 20, 30]])   # Shape (1, 3)

# Add the arrays using broadcasting
result = arr1 + arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult after broadcasting addition:")
print(result)


arr1:
[[1]
 [2]
 [3]]

arr2:
[[10 20 30]]

Result after broadcasting addition:
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [12]:
# Q.40 -- Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
# Ans --
import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([[10, 20],
                 [30, 40]])  # Shape (2, 2)

# To perform element-wise multiplication, we need to ensure the shapes are compatible.
# We can achieve this by reshaping one of the arrays.

# Option 1: Reshape arr2 to align with arr1 for broadcasting
# We want arr2 to broadcast across the columns of arr1.
# Reshape arr2 to (2, 1, 2) so that it can be broadcasted to (2, 3, 2)

# This is a broadcasting-compatible reshape
arr2_reshaped = arr2[:, np.newaxis, :]  # Shape (2, 1, 2)

# Perform the multiplication
result = arr1[:, :, np.newaxis] * arr2_reshaped

print("arr1:")
print(arr1)
print("\narr2 reshaped:")
print(arr2_reshaped)
print("\nResult after broadcasting multiplication:")
print(result)


arr1:
[[1 2 3]
 [4 5 6]]

arr2 reshaped:
[[[10 20]]

 [[30 40]]]

Result after broadcasting multiplication:
[[[ 10  20]
  [ 20  40]
  [ 30  60]]

 [[120 160]
  [150 200]
  [180 240]]]


In [13]:
# Q.41 --  Calculate column wise mean for the given array:
 #      arr = np.array([[1, 2, 3], [4, 5, 6]])
# Ans --
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate column-wise mean
column_wise_mean = np.mean(arr, axis=0)

print("Array:")
print(arr)
print("\nColumn-wise mean:")
print(column_wise_mean)


Array:
[[1 2 3]
 [4 5 6]]

Column-wise mean:
[2.5 3.5 4.5]


In [14]:
# Q.42 -- Find maximum value in each row of the given array:
#          arr = np.array([[1, 2, 3], [4, 5, 6]])
# Ans --
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the maximum value in each row
max_values = np.max(arr, axis=1)

print("Array:")
print(arr)
print("\nMaximum values in each row:")
print(max_values)


Array:
[[1 2 3]
 [4 5 6]]

Maximum values in each row:
[3 6]


In [15]:
# Q.43 --  For the given array, find indices of maximum value in each column.
#          arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the indices of the maximum value in each column
indices_of_max = np.argmax(arr, axis=0)

print("Array:")
print(arr)
print("\nIndices of maximum values in each column:")
print(indices_of_max)


Array:
[[1 2 3]
 [4 5 6]]

Indices of maximum values in each column:
[1 1 1]


In [1]:
# Q.44 -- For the given array, apply custom function to calculate moving sum along rows.
# arr = np.array([[1, 2, 3], [4, 5, 6]])
# Ans -- 
import numpy as np

def moving_sum(arr, window_size):
    """
    Calculate the moving sum along rows of a 2D NumPy array.
    
    Parameters:
    arr (np.ndarray): Input 2D array.
    window_size (int): Size of the moving window.
    
    Returns:
    np.ndarray: Array of moving sums.
    """
    # Initialize an empty list to store results
    result = []
    
    # Iterate over each row in the array
    for row in arr:
        # Compute the moving sum for the current row
        row_moving_sum = np.convolve(row, np.ones(window_size), mode='valid')
        result.append(row_moving_sum)
    
    # Convert the list of results to a NumPy array
    return np.array(result)

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
window_size = 2  # Define your window size here
moving_sums = moving_sum(arr, window_size)

print(moving_sums)

[[ 3.  5.]
 [ 9. 11.]]


In [2]:
# Q.45 -- In the given array, check if all elements in each column are even.
#  arr = np.array([[2, 4, 6], [3, 5, 7]])
# Ans -- 
import numpy as np

# Define the array
arr = np.array([[2, 4, 6], [3, 5, 7]])

# Check if all elements in the array are even
is_even = arr % 2 == 0

# Check if all elements in each column are even
all_even_in_columns = np.all(is_even, axis=0)

print("Array:")
print(arr)
print("Even check (True if even, False otherwise):")
print(is_even)
print("All elements in each column are even:")
print(all_even_in_columns)


Array:
[[2 4 6]
 [3 5 7]]
Even check (True if even, False otherwise):
[[ True  True  True]
 [False False False]]
All elements in each column are even:
[False False False]


In [3]:
# Q.46 -- Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
# original_array = np.array([1, 2, 3, 4, 5, 6])
# Ans --
import numpy as np

# Define the original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Specify dimensions
m = 2  # Number of rows
n = 3  # Number of columns

# Reshape the array
reshaped_matrix = original_array.reshape((m, n))

print("Original array:")
print(original_array)
print("Reshaped matrix:")
print(reshaped_matrix)


Original array:
[1 2 3 4 5 6]
Reshaped matrix:
[[1 2 3]
 [4 5 6]]


In [4]:
# Q.47 -- Create a function that takes a matrix as input and returns the flattened array.
# input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
# Ans--
import numpy as np

def flatten_matrix(matrix):
    """
    Flattens a 2D NumPy array into a 1D NumPy array.
    
    Parameters:
    matrix (np.ndarray): Input 2D array.
    
    Returns:
    np.ndarray: Flattened 1D array.
    """
    return matrix.flatten()

# Example usage
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)

print("Input matrix:")
print(input_matrix)
print("Flattened array:")
print(flattened_array)


Input matrix:
[[1 2 3]
 [4 5 6]]
Flattened array:
[1 2 3 4 5 6]


In [5]:
# Q.48 --  Write a function that concatenates two given arrays along a specified axis.
# array1 = np.array([[1, 2], [3, 4]])
# array2 = np.array([[5, 6], [7, 8]])
# Ans --
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    """
    Concatenates two NumPy arrays along a specified axis.
    
    Parameters:
    array1 (np.ndarray): The first input array.
    array2 (np.ndarray): The second input array.
    axis (int): The axis along which to concatenate. Default is 0.
    
    Returns:
    np.ndarray: The concatenated array.
    """
    return np.concatenate((array1, array2), axis=axis)

# Example usage
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (vertically)
concatenated_array_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:")
print(concatenated_array_axis0)

# Concatenate along axis 1 (horizontally)
concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:")
print(concatenated_array_axis1)


Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [7]:
# Q49 -- Create a function that splits an array into multiple sub-arrays along a specified axis.
# original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Ans--
import numpy as np

def split_array(array, indices_or_sections, axis=0):
    """
    Splits a NumPy array into multiple sub-arrays along a specified axis.
    
    Parameters:
    array (np.ndarray): The input array to be split.
    indices_or_sections (int or list of ints): If an integer, it is the number of equal sections to return.
        If a list of integers, it represents the indices at which to split the array.
    axis (int): The axis along which to split. Default is 0.
    
    Returns:
    list of np.ndarray: The list of sub-arrays resulting from the split.
    """
    return np.array_split(array, indices_or_sections, axis=axis)

# Example usage
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split into 3 parts along axis 0
split_array_axis0 = split_array(original_array, 3, axis=0)
print("Split along axis 0:")
for sub_array in split_array_axis0:
    print(sub_array)

# Split into 2 parts along axis 1
split_array_axis1 = split_array(original_array, 2, axis=1)
print("Split along axis 1:")
for sub_array in split_array_axis1:
    print(sub_array)

# Split using specific indices along axis 0
split_array_axis0_indices = split_array(original_array, [1, 2], axis=0)
print("Split along axis 0 with indices:")
for sub_array in split_array_axis0_indices:
    print(sub_array)


Split along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]
Split along axis 1:
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]
Split along axis 0 with indices:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [8]:
# Q.50 -- Write a function that inserts and then deletes elements from a given array at specified indices.
# original_array = np.array([1, 2, 3, 4, 5])
# indices_to_insert = [2, 4]
# values_to_insert = [10, 11]
# indices_to_delete = [1, 3]
# Ans -- 
import numpy as np

def modify_array(array, indices_to_insert, values_to_insert, indices_to_delete):
    """
    Inserts and then deletes elements from a NumPy array at specified indices.
    
    Parameters:
    array (np.ndarray): The original array.
    indices_to_insert (list of int): The indices at which to insert the values.
    values_to_insert (list of int): The values to insert at the specified indices.
    indices_to_delete (list of int): The indices of the elements to delete.
    
    Returns:
    np.ndarray: The modified array after insertion and deletion.
    """
    # Step 1: Insert elements
    for index, value in zip(sorted(indices_to_insert, reverse=True), values_to_insert):
        array = np.insert(array, index, value)
    
    # Step 2: Delete elements
    array = np.delete(array, indices_to_delete)
    
    return array

# Example usage
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

modified_array = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Original array:")
print(original_array)
print("Modified array:")
print(modified_array)


Original array:
[1 2 3 4 5]
Modified array:
[ 1 11  4 10  5]


In [9]:
# Q.51 -- Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
# Perform element-wise addition between `arr1` and `arr2`.
# Ans-- 
import numpy as np

# Create arr1 with random integers
# Define the shape of arr1
shape = (3, 4)  # Example shape (3 rows, 4 columns)
arr1 = np.random.randint(low=0, high=10, size=shape)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11).reshape((1, 10))

# Adjust the shape of arr2 to match arr1 for element-wise addition
# In this example, we'll use broadcasting to make arr2 have the same shape as arr1
arr2 = np.tile(arr2, (shape[0], 1))[:, :shape[1]]

# Perform element-wise addition
result = arr1 + arr2

# Print the arrays and result
print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult of element-wise addition:")
print(result)


Array arr1:
[[7 5 0 4]
 [8 2 9 6]
 [0 8 6 0]]

Array arr2:
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

Result of element-wise addition:
[[ 8  7  3  8]
 [ 9  4 12 10]
 [ 1 10  9  4]]


In [10]:
# Q.52 -- Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
# from 1 to 10. Subtract `arr2` from `arr1` element-wise.
# Ans-- 
import numpy as np

# Generate arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)  # Starts from 10, ends at 1, with a step of -1

# Generate arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)  # Starts from 1, ends at 10

# Ensure the arrays have the same shape for element-wise operations
# If needed, reshape arr1 and arr2 to be compatible
# For simplicity, both are 1D arrays of the same length

# Perform element-wise subtraction
result = arr1 - arr2

# Print the arrays and result
print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult of element-wise subtraction:")
print(result)


Array arr1:
[10  9  8  7  6  5  4  3  2  1]

Array arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [11]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
# Perform element-wise multiplication between `arr1` and `arr2`.
# Ans -- 
import numpy as np

# Define the shape of arr1
shape = (3, 5)  # Example shape (3 rows, 5 columns)

# Generate arr1 with random integers
arr1 = np.random.randint(low=1, high=10, size=shape)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Adjust the shape of arr2 to match arr1 for element-wise multiplication
# Here we use broadcasting to make arr2 have the same shape as arr1
arr2 = np.tile(arr2, (shape[0], 1))

# Perform element-wise multiplication
result = arr1 * arr2

# Print the arrays and result
print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult of element-wise multiplication:")
print(result)


Array arr1:
[[4 1 7 5 7]
 [6 7 6 5 9]
 [9 9 2 7 5]]

Array arr2:
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]

Result of element-wise multiplication:
[[ 4  2 21 20 35]
 [ 6 14 18 20 45]
 [ 9 18  6 28 25]]


In [12]:
# Q.54 -- Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
# to 5. Perform element-wise division of `arr1` by `arr2`.
# Ans -- 
import numpy as np

# Generate arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)  # This creates an array [2, 4, 6, 8, 10]

# Generate arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)  # This creates an array [1, 2, 3, 4, 5]

# Ensure both arrays have compatible shapes for element-wise operations
# In this case, arr1 has 5 elements and arr2 also has 5 elements,
# so they can be directly divided element-wise.

# Perform element-wise division
result = arr1 / arr2

# Print the arrays and result
print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult of element-wise division:")
print(result)


Array arr1:
[ 2  4  6  8 10]

Array arr2:
[1 2 3 4 5]

Result of element-wise division:
[2. 2. 2. 2. 2.]


In [13]:
# Q.55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
# Ans - 
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)  # This creates an array [1, 2, 3, 4, 5]

# Create arr2 with the same numbers but reversed
arr2 = arr1[::-1]  # This reverses arr1 to [5, 4, 3, 2, 1]

# Perform element-wise exponentiation
result = arr1 ** arr2

# Print the arrays and result
print("Array arr1:")
print(arr1)
print("\nArray arr2 (reversed):")
print(arr2)
print("\nResult of element-wise exponentiation:")
print(result)


Array arr1:
[1 2 3 4 5]

Array arr2 (reversed):
[5 4 3 2 1]

Result of element-wise exponentiation:
[ 1 16 27 16  5]


In [14]:
# Q.56 --  Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
# arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
# Ans -- 
import numpy as np

def count_substring_occurrences(array, substring):
    """
    Counts the occurrences of a specific substring within a NumPy array of strings.
    
    Parameters:
    array (np.ndarray): The NumPy array containing strings.
    substring (str): The substring to count within the array.
    
    Returns:
    int: The total number of occurrences of the substring within the array.
    """
    # Initialize the count
    total_count = 0
    
    # Iterate through each element in the array
    for string in array:
        # Count occurrences of the substring in the current string
        total_count += string.count(substring)
    
    return total_count

# Example usage
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

# Call the function
occurrences = count_substring_occurrences(arr, substring)

# Print the result
print(f"The substring '{substring}' occurs {occurrences} times in the array.")


The substring 'hello' occurs 3 times in the array.


In [17]:
# Q.57. Write a function that extracts uppercase characters from a NumPy array of strings.
# arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
# arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
# Ans -- 
def extract_uppercase_characters(strings):
    """
    Extracts all uppercase characters from a list of strings.
    
    Parameters:
    strings (list of str): The list containing strings.
    
    Returns:
    str: A string containing all uppercase characters extracted from the list.
    """
    # Initialize an empty string to store uppercase characters
    uppercase_chars = ''
    
    # Iterate through each element in the list
    for string in strings:
        # Extract uppercase characters and add them to the result
        uppercase_chars += ''.join([char for char in string if char.isupper()])
    
    return uppercase_chars

# Example usage
strings = ['Hello', 'World', 'OpenAI', 'GPT']

# Call the function
result = extract_uppercase_characters(strings)

# Print the result
print(f"Extracted uppercase characters: {result}")


Extracted uppercase characters: HWOAIGPT


In [18]:
# Q.58 -- Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
# Ans --
import numpy as np

def replace_substring(array, old_substring, new_string):
    """
    Replaces occurrences of a substring in a NumPy array of strings with a new string.
    
    Parameters:
    array (np.ndarray): The NumPy array containing strings.
    old_substring (str): The substring to be replaced.
    new_string (str): The new string to replace the old substring.
    
    Returns:
    np.ndarray: The modified NumPy array with replacements.
    """
    # Create a new array to store the modified strings
    modified_array = np.array([string.replace(old_substring, new_string) for string in array])
    
    return modified_array

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_string = 'orange'

# Call the function
result = replace_substring(arr, old_substring, new_string)

# Print the result
print("Original array:")
print(arr)
print("\nModified array:")
print(result)


Original array:
['apple' 'banana' 'grape' 'pineapple']

Modified array:
['orange' 'banana' 'grape' 'pineorange']


In [22]:
# Q.59 -- Write a function that concatenates strings in a NumPy array element-wise.
# arr1 = np.array(['Hello', 'World'])
# arr2 = np.array(['Open', 'AI'])
# Ans -- 
import numpy as np

def concatenate_strings_elementwise(array1, array2):
    """
    Concatenates strings in two NumPy arrays element-wise.
    
    Parameters:
    array1 (np.ndarray): The first NumPy array containing strings.
    array2 (np.ndarray): The second NumPy array containing strings.
    
    Returns:
    np.ndarray: A NumPy array with concatenated strings.
    """
    # Check if both arrays have the same shape
    if array1.shape != array2.shape:
        raise ValueError("Input arrays must have the same shape.")
    
    # Concatenate corresponding elements element-wise
    concatenated_array = np.char.add(array1, array2)
    
    return concatenated_array

# Example usage
arr1 = np.array(['Hello' , 'World'])
arr2 = np.array(['Open', 'AI'])

# Call the function
result = concatenate_strings_elementwise(arr1,  arr2)

# Print the result
print("Concatenated array: ")
print(result)


Concatenated array: 
['HelloOpen' 'WorldAI']


In [23]:
# Q.60 -- Write a function that finds the length of the longest string in a NumPy array.
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
# Ans --
import numpy as np

def length_of_longest_string(array):
    """
    Finds the length of the longest string in a NumPy array.
    
    Parameters:
    array (np.ndarray): The NumPy array containing strings.
    
    Returns:
    int: The length of the longest string.
    """
    # Get the lengths of all strings in the array
    lengths = np.char.str_len(array)
    
    # Find the maximum length
    max_length = np.max(lengths)
    
    return max_length

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Call the function
longest_length = length_of_longest_string(arr)

# Print the result
print(f"The length of the longest string is: {longest_length}")


The length of the longest string is: 9


In [24]:
# Q.61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
# standard deviation of the dataset using NumPy's functions.
# Ans --
import numpy as np

# Generate a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute the mean
mean = np.mean(dataset)

# Compute the median
median = np.median(dataset)

# Compute the variance
variance = np.var(dataset)

# Compute the standard deviation
std_dev = np.std(dataset)

# Print the results
print(f"Dataset: {dataset}")
print(f"Mean: {mean:.2f}")
print(f"Median: {median:.2f}")
print(f"Variance: {variance:.2f}")
print(f"Standard Deviation: {std_dev:.2f}")


Dataset: [436 737 379 506  51 811 583 289 311 668 685 301 146 529 395  65 532 975
 770 371 271 343 603 836 168 123 691 683 515 907 454 925 442 397 948 457
  79 288  77 925 311 840 864 570  75 536 703 232 809 769 326 671 399 809
 286 186 763 980 829 811 990  69 823 437 634 843 286  84 983 371 108 479
 387  57 518 617  97 494 115 506 516 456  55  34  47 941 156 689 922 964
 766 303  34  72 886  49  73 852 133 948]
Mean: 492.35
Median: 486.50
Variance: 91294.39
Standard Deviation: 302.15


In [25]:
# Q.62 -- Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
# Ans -- 
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
dataset = np.random.randint(1, 101, size=50)

# Calculate the 25th percentile
percentile_25 = np.percentile(dataset, 25)

# Calculate the 75th percentile
percentile_75 = np.percentile(dataset, 75)

# Print the results
print(f"Dataset: {dataset}")
print(f"25th Percentile: {percentile_25:.2f}")
print(f"75th Percentile: {percentile_75:.2f}")


Dataset: [40 92 79 53 58 83 61 64 27 75 21 13 76 27 23 60 28  3 62 49 10 91  5 51
 77 24 92 85 81 15  1 90 35 16 90 19  9 39 15 36 52 74 64  8 39 43 51 19
 17 30]
25th Percentile: 19.50
75th Percentile: 71.50


In [26]:
# Q.63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
# Ans --
import numpy as np

# Create two arrays representing two sets of variables
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([15, 25, 35, 45, 55])

# Compute the correlation coefficient matrix
correlation_matrix = np.corrcoef(array1, array2)

# Extract the correlation coefficient between the two arrays
correlation_coefficient = correlation_matrix[0, 1]

# Print the results
print("Correlation Coefficient Matrix:")
print(correlation_matrix)
print(f"Correlation Coefficient between array1 and array2: {correlation_coefficient:.2f}")


Correlation Coefficient Matrix:
[[1. 1.]
 [1. 1.]]
Correlation Coefficient between array1 and array2: 1.00


In [27]:
# Q.64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
# Ans -- 
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

# Print the result
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of Matrix Multiplication:")
print(result)


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of Matrix Multiplication:
[[ 58  64]
 [139 154]]


In [28]:
# Q.65 Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
# Ans -- 
import numpy as np

# Create an array of 50 integers between 10 and 1000
array = np.random.randint(10, 1001, size=50)

# Calculate the 10th percentile
percentile_10 = np.percentile(array, 10)

# Calculate the 50th percentile (median)
percentile_50 = np.percentile(array, 50)

# Calculate the 90th percentile
percentile_90 = np.percentile(array, 90)

# Calculate the first quartile (25th percentile)
first_quartile = np.percentile(array, 25)

# Calculate the third quartile (75th percentile)
third_quartile = np.percentile(array, 75)

# Print the results
print(f"Array: {array}")
print(f"10th Percentile: {percentile_10:.2f}")
print(f"50th Percentile (Median): {percentile_50:.2f}")
print(f"90th Percentile: {percentile_90:.2f}")
print(f"First Quartile (25th Percentile): {first_quartile:.2f}")
print(f"Third Quartile (75th Percentile): {third_quartile:.2f}")


Array: [420 465 702 909 622 106 183 333 146 740 790 740 725 703 425 318 371  75
 366 396 316 175 928 725  94 923 320 875  42 266 933 384 190 572 308 164
 205 426 103 359 534  93 327 501 935 567 483 131 877 364]
10th Percentile: 105.70
50th Percentile (Median): 390.00
90th Percentile: 880.20
First Quartile (25th Percentile): 220.25
Third Quartile (75th Percentile): 702.75


In [29]:
# Q.66. Create a NumPy array of integers and find the index of a specific element.
# Ans -- 
import numpy as np

# Create a NumPy array of integers
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Define the specific element to find
specific_element = 50

# Find the index of the specific element
indices = np.where(array == specific_element)

# Print the results
print(f"Array: {array}")
print(f"Index of element {specific_element}: {indices[0]}")


Array: [ 10  20  30  40  50  60  70  80  90 100]
Index of element 50: [4]


In [30]:
# Q.67. Generate a random NumPy array and sort it in ascending order.
# Ans -- 
import numpy as np

# Generate a random NumPy array of integers
array = np.random.randint(10, 100, size=20)  # Array of 20 random integers between 10 and 100

# Sort the array in ascending order
sorted_array = np.sort(array)

# Print the results
print(f"Original Array: {array}")
print(f"Sorted Array: {sorted_array}")


Original Array: [96 11 53 97 50 47 34 23 36 35 97 85 64 69 55 82 72 27 63 77]
Sorted Array: [11 23 27 34 35 36 47 50 53 55 63 64 69 72 77 82 85 96 97 97]


In [31]:
# Q.68. Filter elements >20  in the given NumPy array.
# arr = np.array([12, 25, 6, 42, 8, 30])
# Ans -- 
import numpy as np

# Define the NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Apply the condition to filter elements greater than 20
filtered_arr = arr[arr > 20]

# Print the results
print(f"Original Array: {arr}")
print(f"Filtered Array (elements > 20): {filtered_arr}")


Original Array: [12 25  6 42  8 30]
Filtered Array (elements > 20): [25 42 30]


In [32]:
# Q.69. Filter elements which are divisible by 3 from a given NumPy array.
# arr = np.array([1, 5, 8, 12, 15])
# Ans -- 
import numpy as np

# Define the NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Apply the condition to filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]

# Print the results
print(f"Original Array: {arr}")
print(f"Filtered Array (elements divisible by 3): {filtered_arr}")


Original Array: [ 1  5  8 12 15]
Filtered Array (elements divisible by 3): [12 15]


In [33]:
# Q.70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])
# ANS -- 
import numpy as np

# Define the NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Apply the condition to filter elements >= 20 and <= 40
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

# Print the results
print(f"Original Array: {arr}")
print(f"Filtered Array (elements ≥ 20 and ≤ 40): {filtered_arr}")


Original Array: [10 20 30 40 50]
Filtered Array (elements ≥ 20 and ≤ 40): [20 30 40]


In [34]:
# Q.71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
# arr = np.array([1, 2, 3])
# Ans -- 
import numpy as np

# Define the NumPy array
arr = np.array([1, 2, 3])

# Check the byte order using the dtype.byteorder attribute
byte_order = arr.dtype.byteorder

# Print the results
print(f"Array: {arr}")
print(f"Byte Order: '{byte_order}'")


Array: [1 2 3]
Byte Order: '='


In [35]:
# Q.72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
# arr = np.array([1, 2, 3], dtype=np.int32)
# Ans -- 
import numpy as np

# Define the NumPy array with dtype=np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr_byteswapped = arr.byteswap(inplace=True)

# Print the results
print(f"Original Array: {arr}")
print(f"Array After Byte Swapping: {arr_byteswapped}")


Original Array: [16777216 33554432 50331648]
Array After Byte Swapping: [16777216 33554432 50331648]


In [36]:
#  Q.73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
# arr = np.array([1, 2, 3], dtype=np.int32)
# Ans -- 
import numpy as np

# Create the original array with dtype np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Display the original array and its byte order
print("Original array:", arr)
print("Original array dtype:", arr.dtype)
print("Original array byte order:", arr.dtype.byteorder)

# Swap the byte order using newbyteorder()
swapped_arr = arr.newbyteorder()

# Display the new array with swapped byte order
print("Array with swapped byte order:", swapped_arr)
print("Swapped array dtype:", swapped_arr.dtype)
print("Swapped array byte order:", swapped_arr.dtype.byteorder)


Original array: [1 2 3]
Original array dtype: int32
Original array byte order: =
Array with swapped byte order: [16777216 33554432 50331648]
Swapped array dtype: >i4
Swapped array byte order: >


In [37]:
# Q.74 -- 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
# arr = np.array([1, 2, 3], dtype=np.int32)
# Ans -- 
import numpy as np

# Create the original array with dtype np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Display the original array and its byte order
print("Original array:", arr)
print("Original array dtype:", arr.dtype)
print("Original array byte order:", arr.dtype.byteorder)

# Determine the system's endianness
system_endianness = '<' if np.little_endian else '>'

# Swap byte order conditionally based on the system's endianness
if arr.dtype.byteorder != system_endianness:
    swapped_arr = arr.newbyteorder()
else:
    swapped_arr = arr

# Display the new array with swapped byte order (if applicable)
print("Array with conditionally swapped byte order:", swapped_arr)
print("Swapped array dtype:", swapped_arr.dtype)
print("Swapped array byte order:", swapped_arr.dtype.byteorder)


Original array: [1 2 3]
Original array dtype: int32
Original array byte order: =
Array with conditionally swapped byte order: [16777216 33554432 50331648]
Swapped array dtype: >i4
Swapped array byte order: >


In [38]:
# Q.75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
#  arr = np.array([1, 2, 3], dtype=np.int32)
# Ans -- 
import numpy as np

# Create the original array with dtype np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Display the original array and its byte order
print("Original array:", arr)
print("Original array dtype:", arr.dtype)
print("Original array byte order:", arr.dtype.byteorder)

# Determine the system's endianness
system_endianness = '<' if np.little_endian else '>'

# Check if byte swapping is necessary
if arr.dtype.byteorder == '=':
    # Array has native byte order
    swapping_necessary = False
else:
    # Array has non-native byte order
    swapping_necessary = arr.dtype.byteorder != system_endianness

# Output the result
print("System endianness:", system_endianness)
print("Is byte swapping necessary?", swapping_necessary)


Original array: [1 2 3]
Original array dtype: int32
Original array byte order: =
System endianness: <
Is byte swapping necessary? False


In [39]:
# Q.76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
# Ans -- 
import numpy as np

# Create a NumPy array `arr1` with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of `arr1` named `copy_arr`
copy_arr = arr1.copy()

# Modify an element in `copy_arr`
copy_arr[0] = 100  # Change the first element to 100

# Check if modifying `copy_arr` affects `arr1`
print("Original array (arr1):", arr1)
print("Modified copy (copy_arr):", copy_arr)


Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified copy (copy_arr): [100   2   3   4   5   6   7   8   9  10]


In [40]:
# Q.77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
# Ans - 
import numpy as np

# Step 1: Create a 2D NumPy array `matrix` of shape (3, 3) with random integers
matrix = np.random.randint(1, 10, size=(3, 3))

# Step 2: Extract a slice `view_slice` from the matrix
# For demonstration, we'll take a slice of the first two rows and columns
view_slice = matrix[:2, :2]

# Step 3: Modify an element in `view_slice`
view_slice[0, 0] = 100

# Step 4: Observe if the change affects the original `matrix`
print("Original matrix:")
print(matrix)

print("Modified slice (view_slice):")
print(view_slice)


Original matrix:
[[100   5   5]
 [  6   9   2]
 [  1   8   5]]
Modified slice (view_slice):
[[100   5]
 [  6   9]]


In [41]:
# Q.78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
# Ans -- 
import numpy as np

# Step 1: Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape((4, 3))

# Step 2: Extract a slice `view_b` from `array_a`
# For demonstration, we'll take a slice of the first two rows and columns
view_b = array_a[:2, :2]

# Step 3: Broadcast the addition of 5 to `view_b`
view_b += 5

# Step 4: Observe if the change affects the original `array_a`
print("Original array_a:")
print(array_a)

print("Modified view_b:")
print(view_b)


Original array_a:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]
Modified view_b:
[[ 6  7]
 [ 9 10]]


In [42]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
# reflects changes in the original `orig_array`.
# Ans -- 
import numpy as np

# Step 1: Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape((2, 4))

# Step 2: Create a reshaped view `reshaped_view` of shape (4, 2) from `orig_array`
reshaped_view = orig_array.reshape((4, 2))

# Step 3: Modify an element in `reshaped_view`
reshaped_view[0, 0] = 100

# Step 4: Check if the change affects the original `orig_array`
print("Original array (orig_array):")
print(orig_array)

print("Modified reshaped view (reshaped_view):")
print(reshaped_view)


Original array (orig_array):
[[100   2   3   4]
 [  5   6   7   8]]
Modified reshaped view (reshaped_view):
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [43]:
# Q.80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
# Ans -- 
import numpy as np

# Step 1: Create a NumPy array `data` of shape (3, 4) with random integers
data = np.random.randint(1, 20, size=(3, 4))

# Step 2: Extract a copy `data_copy` of elements greater than 5
# Extract elements greater than 5 and create a copy
data_copy = data[data > 5].copy()

# Step 3: Modify an element in `data_copy`
data_copy[0] = 100

# Step 4: Verify if modifying `data_copy` affects the original `data`
print("Original data:")
print(data)

print("Modified copy (data_copy):")
print(data_copy)


Original data:
[[ 2  6  6 13]
 [ 1 10 14 11]
 [15 12 18  8]]
Modified copy (data_copy):
[100   6  13  10  14  11  15  12  18   8]


In [44]:
# Q.81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
# operations between them.
# import numpy as np

# Step 1: Create two matrices A and B of identical shape containing integers
# Let's create two 3x3 matrices for this example
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Step 2: Perform addition between A and B
addition_result = A + B

# Step 3: Perform subtraction between A and B
subtraction_result = A - B

# Print results
print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

print("Addition of A and B:")
print(addition_result)

print("Subtraction of A and B:")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition of A and B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction of A and B:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [45]:
# Q.82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
# Ans -- 
import numpy as np

# Step 1: Generate two matrices C (3x2) and D (2x4)
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

# Step 2: Perform matrix multiplication
# The result of multiplying C (3x2) with D (2x4) will be a matrix of shape (3x4)
result = np.dot(C, D)

# Print results
print("Matrix C (3x2):")
print(C)

print("Matrix D (2x4):")
print(D)

print("Matrix multiplication result (C * D):")
print(result)


Matrix C (3x2):
[[1 2]
 [3 4]
 [5 6]]
Matrix D (2x4):
[[ 7  8  9 10]
 [11 12 13 14]]
Matrix multiplication result (C * D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [46]:
# Q.83. Create a matrix `E` and find its transpose.
# Ans -- 
import numpy as np

# Step 1: Create a matrix E
E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Step 2: Find the transpose of matrix E
E_transpose = E.T

# Alternatively, you can use the np.transpose function
# E_transpose = np.transpose(E)

# Print results
print("Matrix E:")
print(E)

print("Transpose of Matrix E:")
print(E_transpose)


Matrix E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of Matrix E:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [47]:
# Q.84. Generate a square matrix `F` and compute its determinant.
# Ans -- 
import numpy as np

# Step 1: Generate a square matrix F
# Let's create a 3x3 matrix for this example
F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Step 2: Compute the determinant of matrix F
determinant = np.linalg.det(F)

# Print results
print("Matrix F:")
print(F)

print("Determinant of Matrix F:")
print(determinant)


Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of Matrix F:
0.0


In [48]:
# Q.85. Create a square matrix `G` and find its inverse.
#Ans -- 
import numpy as np

# Step 1: Create a square matrix G
# Let's create a 3x3 matrix for this example
G = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Step 2: Compute the inverse of matrix G
# Check if the matrix is invertible by calculating its determinant
determinant = np.linalg.det(G)

if determinant != 0:
    G_inverse = np.linalg.inv(G)
else:
    G_inverse = "Matrix is singular and cannot be inverted."

# Print results
print("Matrix G:")
print(G)

print("Inverse of Matrix G:")
print(G_inverse)


Matrix G:
[[1 2 3]
 [0 1 4]
 [5 6 0]]
Inverse of Matrix G:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
